# vim: ft=make

SRCDIR=src

include Makefile.common

OBJS=$(addprefix $(OBJDIR)/, $(LIBNAME).o $(LIBNAME)_private.o $(ERRNAME).o)

ALIB=$(LIBDIR)/lib$(LIBNAME).a

SOBASENAME=lib$(LIBNAME).so
SOLIBNAME=lib$(LIBNAME).so.$(VERSION_MAJOR)
SOLIB=$(SOBASENAME).$(VERSION)

SOFILES=$(addprefix $(LIBDIR)/, $(SOLIB) $(SOLIBNAME) $(SOBASENAME))

vpath %.h $(SRCDIR)

CXXFLAGS=-fPIC -fvisibility=hidden
LDFLAGS=-shared -Wl,-soname=$(SOLIBNAME)

libs: $(ALIB) solib

solib: $(SOFILES)

$(ALIB): $(OBJS) | $(LIBDIR)
	$(AR) cr $@ $^

$(OBJDIR)/$(LIBNAME).o: $(LIBNAME)_private.h

$(LIBDIR)/$(SOLIB): $(OBJS) | $(LIBDIR)
	$(CXX) $(LDFLAGS) $^ $(LOADLIBES) $(LDLIBS) -o $@

$(LIBDIR)/$(SOLIBNAME): $(LIBDIR)/$(SOLIB)
	ln -sf $(<F) $@

$(LIBDIR)/$(SOBASENAME): $(LIBDIR)/$(SOLIBNAME)
	ln -sf $(<F) $@

clean:
	-rm -rf $(LIBDIR)

.PHONY: libs solib

